# Generated by Django 2.2.4 on 2019-08-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Events_Main_Img', models.ImageField(upload_to='static/nehal/images/')),
            ],
        ),
    ]
