# Generated by Django 2.2.4 on 2019-08-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='directUrl',
            field=models.CharField(default='asdadsd', max_length=100),
        ),
    ]
