# Generated by Django 2.2.4 on 2019-08-28 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_events_directurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='Events_Main_Img',
        ),
    ]
