# Generated by Django 2.2.4 on 2019-08-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_events_events_main_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='address',
            field=models.CharField(default='cde', max_length=100),
        ),
        migrations.AddField(
            model_name='events',
            name='description',
            field=models.CharField(default='abc', max_length=500),
        ),
        migrations.AddField(
            model_name='events',
            name='endDate',
            field=models.CharField(default='6/5/2019', max_length=50),
        ),
        migrations.AddField(
            model_name='events',
            name='endTime',
            field=models.CharField(default='15:00pm', max_length=50),
        ),
        migrations.AddField(
            model_name='events',
            name='startDate',
            field=models.CharField(default='5/5/2019', max_length=50),
        ),
        migrations.AddField(
            model_name='events',
            name='startTime',
            field=models.CharField(default='15:00pm', max_length=50),
        ),
        migrations.AddField(
            model_name='events',
            name='venue',
            field=models.CharField(default='bcd', max_length=100),
        ),
    ]
