# Generated by Django 2.2.4 on 2019-09-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('directUrl', models.CharField(default='asdadsd', max_length=100)),
                ('description', models.CharField(default='abc', max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Iconic',
        ),
    ]
