# Generated by Django 2.2.4 on 2019-08-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayText', models.CharField(max_length=100)),
                ('imageUrl', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayText', models.CharField(max_length=100)),
                ('videoUrl', models.CharField(max_length=500)),
            ],
        ),
    ]
